"""Regenerate ``core/include/rumi/epsg_kinds.def`` from the EPSG registry.

rumi must distinguish geographic and projected CRSs to select the correct
GeoKeys. EPSG code ranges are not sufficient for that classification, so this
script emits the registry result as sorted closed ranges.

    pip install pyproj
    python tools/gen_epsg_kinds.py > core/include/rumi/epsg_kinds.def
"""

import sys
from datetime import UTC, datetime

from pyproj import __proj_version__
from pyproj.database import query_crs_info


def runs(codes):
    codes = sorted(codes)
    out, start, prev = [], codes[0], codes[0]
    for c in codes[1:]:
        if c != prev + 1:
            out.append((start, prev))
            start = c
        prev = c
    out.append((start, prev))
    return out


def main():
    kinds = {"GEOGRAPHIC": [], "PROJECTED": []}
    for row in query_crs_info(auth_name="EPSG", allow_deprecated=False):
        kind = str(row.type).split(".")[-1].lower()
        if "geographic" in kind:
            kinds["GEOGRAPHIC"].append(int(row.code))
        elif "projected" in kind:
            kinds["PROJECTED"].append(int(row.code))

    w = sys.stdout.write
    w("/* Generated by tools/gen_epsg_kinds.py, do not edit.\n"
      f" * EPSG via PROJ {__proj_version__}, "
      f"{datetime.now(UTC).date().isoformat()}.\n"
      " *\n"
      " * Geographic and projected EPSG codes, stored as closed ranges. */\n\n")

    for name, codes in kinds.items():
        r = runs(codes)
        w(f"/* {len(codes)} codes, {len(r)} ranges */\n")
        w(f"RUMI_EPSG_BEGIN({name})\n")
        for lo, hi in r:
            w(f"RUMI_EPSG_RANGE({name}, {lo:5}, {hi:5})\n")
        w(f"RUMI_EPSG_END({name})\n\n")


if __name__ == "__main__":
    main()
