"""Regenerates core/include/rumi/epsg_kinds.def from the EPSG registry.

Writing a CRS needs one bit per code, geographic or projected, since that picks
GTModelType and which of GeographicType / ProjectedCSType carries the code.
The number does not answer it. EPSG:4037 sits in the middle of the geographic
block and is projected, and it is not alone. Hence a table, emitted as sorted
closed ranges so it costs a few kilobytes and a binary search.

    pip install pyproj
    python tools/gen_epsg_kinds.py > core/include/rumi/epsg_kinds.def
"""

import sys
from datetime import UTC, datetime

from pyproj import __proj_version__
from pyproj.database import query_crs_info


def runs(codes):
    codes = sorted(codes)
    out, start, prev = [], codes[0], codes[0]
    for c in codes[1:]:
        if c != prev + 1:
            out.append((start, prev))
            start = c
        prev = c
    out.append((start, prev))
    return out


def main():
    kinds = {"GEOGRAPHIC": [], "PROJECTED": []}
    for row in query_crs_info(auth_name="EPSG", allow_deprecated=False):
        kind = str(row.type).split(".")[-1].lower()
        if "geographic" in kind:
            kinds["GEOGRAPHIC"].append(int(row.code))
        elif "projected" in kind:
            kinds["PROJECTED"].append(int(row.code))

    w = sys.stdout.write
    w("/* Generated by tools/gen_epsg_kinds.py, do not edit.\n"
      f" * EPSG via PROJ {__proj_version__}, "
      f"{datetime.now(UTC).date().isoformat()}.\n"
      " *\n"
      " * Which kind of CRS each code names, as closed ranges. A code in\n"
      " * neither table needs its GeoTIFF keys passed in directly. */\n\n")

    for name, codes in kinds.items():
        r = runs(codes)
        w(f"/* {len(codes)} codes, {len(r)} ranges */\n")
        w(f"RUMI_EPSG_BEGIN({name})\n")
        for lo, hi in r:
            w(f"RUMI_EPSG_RANGE({name}, {lo:5}, {hi:5})\n")
        w(f"RUMI_EPSG_END({name})\n\n")


if __name__ == "__main__":
    main()
